#!/usr/bin/env python3
"""
Filter character CSV file by character type (ASCII or CJK).
Reads a CSV file generated by dump_char_csv.py and filters rows based on codepoint type.
"""
import argparse
import csv
import sys
from utils import is_ascii_char, is_cjk_char


def filter_csv(input_csv, char_type, output_csv):
    """
    Filter CSV file by character type.
    
    Args:
        input_csv: Path to input CSV file (from dump_char_csv.py)
        char_type: Type of characters to keep ('ascii' or 'cjk')
        output_csv: Path to output filtered CSV file
    """
    # Determine which filter function to use
    if char_type == 'ascii':
        filter_func = is_ascii_char
    elif char_type == 'cjk':
        filter_func = is_cjk_char
    else:
        print(f"Error: Invalid character type '{char_type}'. Must be 'ascii' or 'cjk'.", file=sys.stderr)
        sys.exit(1)
    
    try:
        # Read input CSV
        with open(input_csv, 'r', encoding='utf-8', newline='') as infile:
            reader = csv.DictReader(infile)
            fieldnames = reader.fieldnames
            
            if not fieldnames or 'codepoint_dec' not in fieldnames:
                print("Error: Invalid CSV format. Missing 'codepoint_dec' column.", file=sys.stderr)
                sys.exit(1)
            
            # Filter rows and write to output
            filtered_rows = []
            for row in reader:
                try:
                    codepoint = int(row['codepoint_dec'])
                    if filter_func(codepoint):
                        filtered_rows.append(row)
                except (ValueError, KeyError) as e:
                    print(f"Warning: Skipping invalid row: {e}", file=sys.stderr)
                    continue
        
        # Write filtered output
        with open(output_csv, 'w', encoding='utf-8', newline='') as outfile:
            writer = csv.DictWriter(outfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(filtered_rows)
        
        print(f"Filtered {len(filtered_rows)} {char_type} characters from {input_csv} to {output_csv}")
        
    except FileNotFoundError:
        print(f"Error: Input file '{input_csv}' not found.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Filter character CSV file by character type (ASCII or CJK).'
    )
    parser.add_argument(
        'input_csv',
        help='Input CSV file generated by dump_char_csv.py'
    )
    parser.add_argument(
        'type',
        choices=['ascii', 'cjk'],
        help='Character type to filter: ascii or cjk'
    )
    parser.add_argument(
        'output_csv',
        help='Output filtered CSV file'
    )
    
    args = parser.parse_args()
    
    filter_csv(args.input_csv, args.type, args.output_csv)


if __name__ == '__main__':
    main()
